In [16]:
#Q4

class A:
    def _init_(self, i=0):
        self.i = i

    def ml(self):
        self.i += 1


class B(A):
    def _init_(self, j=0):
        super()._init_(3)
        self.j = j

    def ml(self):
        self.i += 1


def main():
    b = B()
    b.ml()
    print(b.i)
    print(b.j)


main()

AttributeError: 'B' object has no attribute 'i'

In [14]:
#Q5
try:
    ST = 10 * [0]
    x = ST[9]
    print("Done")
except IndexError:
    print("Index out of bound")
else:
    print("Nothing is wrong")
finally:
    print("Finally we are here")
    
print("Continue")

Done
Nothing is wrong
Finally we are here
Continue


In [6]:
#Q3

a = 'A4D6F'
b = 1234
scale = 16
res = bin(int(a, scale))
print(res, "- in binary")
print(hex(b), "- in hexadecimal")

0b10100100110101101111 - in binary
0x4d2 - in hexadecimal


In [8]:
#Q2

r1=int(4)
r2=int(5)
r3=int(7)
r4=int(5)
ri=(6)
emf=int(12)
r=11+0.59
z=emf/r
print("current:",z)
v=emf+z*ri
print("terminal voltage:",v)

current: 1.0353753235547887
terminal voltage: 18.21225194132873


In [9]:
#Q1

import numpy as np
m1 = np.array([[3,9,8,7,6],[6,3,9,8,7],[7,6,3,9,8],[9,8,7,6,3]])
print(m1)

[[3 9 8 7 6]
 [6 3 9 8 7]
 [7 6 3 9 8]
 [9 8 7 6 3]]
